#ifndef MATHEMATICALMODEL_GLOBAL_H
#define MATHEMATICALMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATHEMATICALMODEL_LIBRARY)
#  define MATHEMATICALMODEL_EXPORT Q_DECL_EXPORT
#else
#  define MATHEMATICALMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MATHEMATICALMODEL_GLOBAL_H
